learning_rate: 0.0005
batch_size: 64
sigma: 500
experience_replay: 24
seed_results_yaml: "../gflownet_gfm/results/results_gflownet_albuterol_similarity_0.yaml"
seed_top_k: 200
seed_min_score: 0.0
seed_batch_size: 256
