learning_rate: 0.0005
batch_size: 64
sigma: 200
experience_replay: 24
objective_mix_lambda: 0.4
objective_mode: hybrid
reinvent_loss_coef: 0.5
flow_loss_coef: 4.0
beta_init: 2.0
beta_rate: 0.002
beta_max: 40.0
r_min: 0.01
warmup_reinvent_steps: 200
log_every: 100
flow_replay_size: 20000
flow_batch_size: 128
priority_alpha: 0.7
priority_eps: 0.000001
flow_target_tau: 0.005
max_seq_len: 140
terminal_only_oracle: true
