learning_rate: 0.0005
batch_size: 64
sigma: 500
experience_replay: 24
objective_mix_lambda: 0.6
objective_mode: hybrid
reinvent_loss_coef: 1.0
flow_loss_coef: 1.0
beta_init: 1.0
beta_rate: 0.008
beta_max: 25.0
r_min: 0.0001
warmup_reinvent_steps: 200
log_every: 100
flow_replay_size: 20000
flow_batch_size: 128
priority_alpha: 1.0
priority_eps: 0.000001
flow_target_tau: 0.01
max_seq_len: 140
terminal_only_oracle: true
